dags:
  gitSync:
    enabled: true
    # repo: https://github.com/airscholar/Kubernetes-For-DataEngineering.git
    repo: https://github.com/OmarAlSaghier/Kubernetes-For-DataEngineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"